# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/imu.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'proto/imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from py.proto import vector_pb2 as proto_dot_vector__pb2
from py.proto import quaternion_pb2 as proto_dot_quaternion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/imu.proto\x12\x05kevin\x1a\x12proto/vector.proto\x1a\x16proto/quaternion.proto\"\xe1\x01\n\x03Imu\x12\x17\n\x06\x61\x63\x63\x65ls\x18\x01 \x01(\x0b\x32\x07.Vector\x12\x16\n\x05gyros\x18\x02 \x01(\x0b\x32\x07.Vector\x12\x15\n\x04mags\x18\x03 \x01(\x0b\x32\x07.Vector\x12 \n\x0borientation\x18\x04 \x01(\x0b\x32\x0b.Quaternion\x12\x10\n\x08imu_temp\x18\x05 \x01(\x01\x12\x13\n\x0btemperature\x18\x06 \x01(\x01\x12\x10\n\x08pressure\x18\x07 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x08 \x01(\x01\x12\x12\n\ncalibrated\x18\t \x01(\x08\x12\x11\n\ttimestamp\x18\n \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMU']._serialized_start=71
  _globals['_IMU']._serialized_end=296
# @@protoc_insertion_point(module_scope)
